### ISSUE TITLE
Go Forum  Problems using database/sql with denisenkom/go-mssqldb

### ISSUE THREAD

**Issue by carlca** [denisenkom/go-mssqldb#320]
```
macOS 10.13.1 High Sierra
Golang 1.9.2
Docker Toolbox
microsoft/mssql-server-linux:2017-latest

```
Hello. I've been using database/sql combined with denisenkom/go-mssqldb with a reasonable amount of success, but there are one or two glitches as I shall explain. I've had an issue active on the Golang forum for a couple of days but there's been no real response yet. I shall try to reproduce the essence of the issue here.

I have the following client code:

```
package main

import (
	q "github.com/carlca/bigdata/sqlserver"
	_ "github.com/denisenkom/go-mssqldb"
)

func main() {
	db := q.Connect()
	defer db.Close()
	tx := db.NewTx()
	tx.Exec("DROP TABLE IF EXISTS Company")
	tx.Exec(`CREATE TABLE Company
		(ProductID int PRIMARY KEY NOT NULL,
		ProductName varchar(25) NOT NULL,
		Price money NULL,
		Price2 money NULL,		
		ProductDescription text NULL)`)
	tx.CommitTx()
}

```
I also have the following library code:

```
package sqlserver

import (
	"database/sql"
	"flag"
	"fmt"

	e "github.com/carlca/utils/essentials"
)

var (
	debug    = flag.Bool("debug", false, "enable debugging")
	password = flag.String("password", "", "the database password")
	port     = flag.Int("port", 1433, "the database port")
	server   = flag.String("server", "", "the database server")
	user     = flag.String("user", "", "the database user")
)

// DB inherits from sql.DB
type DB struct {
	*sql.DB
}

// Exec combines Prepare and Exec methods
func (db *DB) Exec(cmd string) {
	stmt, err := db.Prepare(cmd)
	e.CheckError("prepare: "+cmd+" failed", err)
	_, err = stmt.Exec()
	e.CheckError("exec: "+cmd+" failed", err)
	if *debug {
		fmt.Printf("exec: %v succeeded\n", cmd)
	}
}

// NewTx wraps the *DB.Begin func
func (db *DB) NewTx() *Tx {
	tnx, err := db.Begin()
	e.CheckError("BeginTx failed: ", err)
	if *debug {
		fmt.Printf("NewTx: succeeded\n")
	}
	return &Tx{*tnx}
}

// Tx inherits from sql.Tx
type Tx struct {
	sql.Tx
}

// Exec wraps *Tx.Exec
func (tx *Tx) Exec(cmd string) {
	stmt, err := tx.Prepare(cmd)
	e.CheckError("prepare: "+cmd+" failed", err)
	_, err = stmt.Exec()
	e.CheckError("exec: "+cmd+" failed", err)
	if *debug {
		fmt.Printf("exec: %v succeeded\n", cmd)
	}
}

// CommitTx wraps the *Tx.Commit func
func (tx *Tx) CommitTx() {
	err := tx.Commit()
	e.CheckError("tx.CommitTx failed: ", err)
	if *debug {
		fmt.Printf("tx.CommitTx succeeded\n")
	}
}

// Connect establishes contact with an SQL Server
func Connect() *DB {
	// parse command line flags
	flag.Parse()
	// dump flags if debug
	if *debug {
		fmt.Printf("password: %s\n", *password)
		fmt.Printf("port: %d\n", *port)
		fmt.Printf("server: %s\n", *server)
		fmt.Printf("user: %s\n", *user)
	}
	// build connection string
	connString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%d", *server, *user, *password, *port)
	// if debug dump connection string
	if *debug {
		fmt.Printf("connString: %s\n", connString)
	}
	// create an SQL Server connection
	dbx, err := sql.Open("mssql", connString)
	e.CheckError("Open DB failed: ", err)
	if *debug {
		fmt.Printf("open mssql: succeeded\n")
	}
	err = dbx.Ping()
	e.CheckError("db.Ping failed", err)
	return &DB{dbx}
}

```
and

```
package essentials

import (
	"fmt"
	"log"

	"github.com/pkg/errors"
)

// CheckError is function to check error with call stack
func CheckError(msg string, err error) {
	if err != nil {
		log.Fatal(fmt.Sprintf("%v: %+v", msg, errors.WithStack(err)))
	}
}
```
The problem is that I’m getting intermittant failure at the end of the client code. It says “panic: sql: connection returned that was never out”. When this occurs, however, if I wait a couple of seconds and run the client program again, it runs without failure.

The error message comes from a func *DB.putConn in sql.go, and seems to be a state dependent issue that occurs depending on timing.

I’ve had a search on Google but, apart from some mentions from github.com/go from 2012 or thereabouts, I cannot find any relevant references.

```
func (db *DB) putConn(dc *driverConn, err error) {
	db.mu.Lock()
	if !dc.inUse {
		if debugGetPut {
			fmt.Printf("putConn(%v) DUPLICATE was: %s\n\nPREVIOUS was: %s", dc, stack(), db.lastPut[dc])
		}
		panic("sql: connection returned that was never out")
	}
	if debugGetPut {
		db.lastPut[dc] = stack()
	}
	dc.inUse = false

	for _, fn := range dc.onPut {
		fn()
	}
	dc.onPut = nil

	if err == driver.ErrBadConn {
		// Don't reuse bad connections.
		// Since the conn is considered bad and is being discarded, treat it
		// as closed. Don't decrement the open count here, finalClose will
		// take care of that.
		db.maybeOpenNewConnections()
		db.mu.Unlock()
		dc.Close()
		return
	}
	if putConnHook != nil {
		putConnHook(db, dc)
	}
	added := db.putConnDBLocked(dc, nil)
	db.mu.Unlock()

	if !added {
		dc.Close()
	}
}

```

It’s worth pointing out that when the code fails, it is failing at a point after the occurrence of the very last item in the client code, namely the call to tx.CommitTx. The debug info and error message is:

```
go run simple.go -debug=true -server=192.168.99.100 -password=<MyPassword> -user=sa
password: <MyPassword>
port: 1433
server: 192.168.99.100
user: sa
connString: server=192.168.99.100;user id=sa;password=<MyPassword>;port=1433
open mssql: succeeded
NewTx: succeeded
exec: DROP TABLE IF EXISTS Company succeeded
exec: CREATE TABLE Company
                (ProductID int PRIMARY KEY NOT NULL,
                ProductName varchar(25) NOT NULL,
                Price money NULL,
                Price2 money NULL,
                ProductDescription text NULL) succeeded
tx.CommitTx succeeded
panic: sql: connection returned that was never out

goroutine 20 [running]:
database/sql.(*DB).putConn(0xc420098140, 0xc4202ae000, 0x14008a0, 0xc42004a1d0)
        /usr/local/go/src/database/sql/sql.go:1054 +0x202
database/sql.(*driverConn).releaseConn(0xc4202ae000, 0x14008a0, 0xc42004a1d0)
        /usr/local/go/src/database/sql/sql.go:380 +0x47
database/sql.(*driverConn).(database/sql.releaseConn)-fm(0x14008a0, 0xc42004a1d0)
        /usr/local/go/src/database/sql/sql.go:643 +0x3e
database/sql.(*Tx).close(0xc4202ca000, 0x14008a0, 0xc42004a1d0)
        /usr/local/go/src/database/sql/sql.go:1720 +0x91
database/sql.(*Tx).rollback(0xc4202ca000, 0x1, 0x0, 0x1057b91)
        /usr/local/go/src/database/sql/sql.go:1807 +0xef
database/sql.(*Tx).awaitDone(0xc4202ca000)
        /usr/local/go/src/database/sql/sql.go:1701 +0x5e
created by database/sql.(*DB).beginDC
        /usr/local/go/src/database/sql/sql.go:1451 +0x216
exit status 2

```
Also, I tried rearranging the client code with defer tx.CommitTx like so:

```
func main() {
	db := q.Connect()
	defer db.Close()
	tx := db.NewTx()
	defer tx.CommitTx()
	tx.Exec("DROP TABLE IF EXISTS Company")
	tx.Exec(`CREATE TABLE Company
		(ProductID int PRIMARY KEY NOT NULL,
		ProductName varchar(25) NOT NULL,
		Price money NULL,
		Price2 money NULL,		
		ProductDescription text NULL)`)
}
```

When I ran it. It failed twice in quick succession and then ran without error the third and subsequent times.

**Comment by kardianos** [comment]
This does seem odd. Can you reproduce it without the extra packages involved?

I'm also confused about the method names, the q.Connect() appears to return a "database/sql".DB struct, but the methods you list aren't on that struct. It is also odd that the name inside q.Connect calls *sql.DB a "conn" variable, when it is really a connection pool.

**Comment by carlca** [comment]
Thanks for the reply!

> This does seem odd. Can you reproduce it without the extra packages involved?

I was hoping to introduce some more logging and debugging information, that's all.

On 3 Dec 2017, 22:23 +0000, Daniel Theophanes <notifications@github.com>, wrote:
> I'm also confused about the method names, the q.Connect() appears to return a "database/sql".DB struct, but the methods you list
No, the q.Connect returns my own DB struct which has an embedded "database/sql".DB struct but with additional methods, such as NewTx(). You can ignore the new DB.Exec function as that is not used
> aren't on that struct. It is also odd that the name inside q.Connect calls *sql.DB a "conn" variable, when it is really a connection pool.
I’m not sure which variable you’re referring to here. Which variable “is really a connection pool”?

I’m using dbx, err := sql.Open("mssql", connString)
To create the dbx variable which is an instance of "database/sql”.DB struct which is later used as  the basis of the returned “sqlserver”.DB (my own derived struct) instance.

Would it help if I put a "go get”…able version of the code up on Github.com?

Thanks,
Carl

**Comment by carlca** [comment]
If so do `go get github.com/carlca/bigdata` and `go get github.com/carlca/utils`.
Then `cd carlca/bigdata/sqltest` and the client file `simple.go` should be there.

**Comment by carlca** [comment]
There’s a badly worded comment there that says:
// create an SQL Server connection

whereas it should say something like:
// create a "database/sql".DB variable

**Comment by kardianos** [comment]
I'm unable to reproduce regardless of how many times I run it. My output:

```
daniel@conk ~/s/g/c/b/sqltest> ./run.sh 
password: 
port: 1433
server: 127.0.0.1
user: sa
connString: 
open sqlserver: succeeded
NewTx: succeeded
exec: DROP TABLE IF EXISTS Company succeeded
exec: CREATE TABLE Company
		(ProductID int PRIMARY KEY NOT NULL,
		ProductName varchar(25) NOT NULL,
		Price money NULL,
		Price2 money NULL,		
		ProductDescription text NULL) succeeded
tx.CommitTx succeeded
```

That being said, I'm also running Go from master, not go1.9.2, so it is slightly different.

**Comment by kardianos** [comment]
Also, if you're using SQL Server, you're wasting time creating Stmts. Just execute the sql directly, the server will cache plans and all that jazz.

**Comment by carlca** [comment]
Thanks a lot for trying Daniel. It's also different because, as mentioned, I'm running SQL Server as the Linux version in a Docker container on an Apple Mac.

I'll try your suggestion of abandoning the Stmts and see how that goes.

**Comment by kardianos** [comment]
I'm running SQL Server on Linux directly. But that really shouldn't make a difference. The first go1.10 beta will be released soon. When they come out please download and try them on that. Thanks.

**Comment by carlca** [comment]
I had a big refactoring session and simplified a lot of things. My client code is now:

```
package main

import (
	q "github.com/carlca/bigdata/sqlserver"
	e "github.com/carlca/utils/essentials"
)

func main() {
	dbase, debug := q.Connect()
	defer dbase.Close()
	tx, err := dbase.Begin()
	e.CheckError("dbase.Begin()", err, debug)
	defer tx.Commit()
	_, err = tx.Exec("DROP TABLE IF EXISTS Company")
	e.CheckError("DROP TABLE", err, debug)
	_, err = tx.Exec(`CREATE TABLE Company
		(ProductID int PRIMARY KEY NOT NULL,
		ProductName varchar(25) NOT NULL,
		Price money NULL,
		Price2 money NULL,		
		ProductDescription text NULL)`)
	e.CheckError("CREATE TABLE", err, debug)
}

```
and my library code is:

```
package sqlserver

import (
	"database/sql"
	"flag"
	"fmt"

	e "github.com/carlca/utils/essentials"
	// MSSQL driver
	_ "github.com/denisenkom/go-mssqldb"
)

var (
	debug    = flag.Bool("debug", false, "enable debugging")
	password = flag.String("password", "", "the database password")
	port     = flag.Int("port", 1433, "the database port")
	server   = flag.String("server", "", "the database server")
	user     = flag.String("user", "", "the database user")
)

// DB inherits from sql.DB
type DB struct {
	*sql.DB
}

// Connect establishes contact with an SQL Server
func Connect() (*DB, bool) {
	// parse command line flags
	flag.Parse()
	// dump flags if debug
	if *debug {
		fmt.Printf("password: %s\n", *password)
		fmt.Printf("port: %d\n", *port)
		fmt.Printf("server: %s\n", *server)
		fmt.Printf("user: %s\n", *user)
	}
	// build connection string
	connString := fmt.Sprintf("server=%s;user id=%s;password=%s;port=%d", *server, *user, *password, *port)
	// if debug dump connection string
	if *debug {
		fmt.Printf("connString: %s\n", connString)
	}
	// create an SQL Server connection
	dbx, err := sql.Open("mssql", connString)
	e.CheckError("Open DB", err, *debug)
	err = dbx.Ping()
	e.CheckError("db.Ping", err, *debug)
	return &DB{dbx}, *debug
}

```
and:

```
package essentials

import (
	"fmt"
	"log"

	"github.com/pkg/errors"
)

// CheckError is function to check error with call stack
func CheckError(msg string, err error, both bool) {
	if both {
		if err == nil {
			fmt.Println(fmt.Sprintf("%v succeeded", msg))
		} else {
			log.Fatal(fmt.Sprintf("%v failed: %+v", msg, errors.WithStack(err)))
		}
	} else {
		if err != nil {
			log.Fatal(fmt.Sprintf("%v failed: %+v", msg, errors.WithStack(err)))
		}
	}
}

```
The intermittant problem has disappeared it seems. I think I was trying to be too clever before with too many DB adn Tx funcs being wrapped for the sake of error checking. Now I think I've still got sufficient error checking with the advantage that the code runs error free.

My next project is to create a PostgreSQL equivalent using the `github.com/lib/pq` library. Hopefully the abstrations provided by the `database/sql` library should make this really easy!!
