### ISSUE TITLE
Reset bad connections

### ISSUE THREAD

**Issue by jozuenoon** [denisenkom/go-mssqldb#536]
**Is your feature request related to a problem? Please describe.**
I'm hitting following panic:
```
panic: driver.ErrBadConn in checkBadConn. This should not happen.
goroutine 117 [running]:
github.com/denisenkom/go-mssqldb.(*Conn).checkBadConn(0xc00005b2c0, 0xe90100, 0xc0000282e0, 0xe90100, 0xc0000282e0)
    /go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20190806190131-db2462fef53b/mssql.go:184 +0x1ca
github.com/denisenkom/go-mssqldb.(*Conn).begin(0xc00005b2c0, 0xea1900, 0xc0003107e0, 0x409900, 0xc13cc0, 0xcbeb80, 0x536401, 0x7f00bc513260)
    /go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20190806190131-db2462fef53b/mssql.go:288 +0xbc
github.com/denisenkom/go-mssqldb.(*Conn).BeginTx(0xc00005b2c0, 0xea1900, 0xc0003107e0, 0x0, 0xc00005b200, 0x1, 0x12, 0x8bb2c97000, 0x0)
    /go/pkg/mod/github.com/denisenkom/go-mssqldb@v0.0.0-20190806190131-db2462fef53b/mssql.go:946 +0x7e
database/sql.ctxDriverBegin(0xea1900, 0xc0003107e0, 0x0, 0xe9d600, 0xc00005b2c0, 0xc0003f13d0, 0x42ab2f, 0xc000000008, 0xc00005b7c0)
    /usr/local/go/src/database/sql/ctxutil.go:106 +0x9e
database/sql.(*DB).beginDC.func1()
    /usr/local/go/src/database/sql/sql.go:1653 +0x6b
database/sql.withLock(0xe97480, 0xc000634c00, 0xc0003f1450)
    /usr/local/go/src/database/sql/sql.go:3097 +0x63
database/sql.(*DB).beginDC(0xc0003fc0c0, 0xea1900, 0xc0003107e0, 0xc000634c00, 0xc000662060, 0x0, 0x0, 0x0, 0x0)
    /usr/local/go/src/database/sql/sql.go:1652 +0xac
database/sql.(*DB).begin(0xc0003fc0c0, 0xea1900, 0xc0003107e0, 0x0, 0x7f00bc7abf01, 0x1000, 0x20300000000000, 0x8000)
    /usr/local/go/src/database/sql/sql.go:1646 +0xd3
database/sql.(*DB).BeginTx(0xc0003fc0c0, 0xea1900, 0xc0003107e0, 0x0, 0x8000000000000107, 0x1, 0x0)
    /usr/local/go/src/database/sql/sql.go:1624 +0x89
```

**Describe the solution you'd like**
https://github.com/denisenkom/go-mssqldb/blob/44cdfe8d8ba9a7322b38cd8fbb0f2cb445e65a69/mssql.go#L184

By following comments on the code above I discovered that it might be somehow fixed by using [ResetSessioner](https://go-review.googlesource.com/c/go/+/73033/), to handle bad connections? Simple search on code base didn't show up any related phrases so I'm assuming this is not in use currently?

**Comment by chris-rossi** [comment]
Hi @jozuenoon, I'll look further into this.

**Comment by jozuenoon** [comment]
@chris-rossi Thanks! Any thoughts regarding this issue?

**Comment by dwj300** [comment]
we are hitting the same issue, which has caused panics in production.

**Comment by chris-rossi** [comment]
@jozuenoon sorry for the delay, we have implemented [SessionResetter](https://github.com/denisenkom/go-mssqldb/blob/44cdfe8d8ba9a7322b38cd8fbb0f2cb445e65a69/mssql_go110.go#L14), which is supported in go 1.10 and above. They decided to change the [name](https://go-review.googlesource.com/c/go/+/78127) which is why you didn't find it. I'm still looking into how the panic is being hit but I hope this helps.

**Comment by excavador** [comment]
@chris-rossi SessionResetter does not help, same problem

**Comment by excavador** [comment]
I think I understand, how to reproduce.

If you use driver in this way
```
	var conn *sql.Conn
	if conn, err = db.Conn(ctx); err != nil {
		return
	}
	defer conn.Close()
	if err = conn.PingContext(ctx); err != nil {
		return
	}
	var tx *sql.Tx
	if tx, err = conn.BeginTx(ctx, nil); err != nil {
		return
	}
```

everything works fine.

But following usage of the driver trigger the issue's problem
```
	var tx *sql.Tx
	if tx, err = db.BeginTx(ctx, nil); err != nil {
		return
	}
```

**Comment by kardianos** [comment]
@excavador If I understand you correctly, the following will reproduce this:

```
ctx, cancel := context.WithCancel(context.Background())
defer cancel()

db, err := sql.OpenDB(...)
if err != nil {
	return err
}
defer db.Close()

var tx *sql.Tx
if tx, err = db.BeginTx(ctx, nil); err != nil {
	return err
}
return nil
```

Or is there more to it?
Is there a way you can reproduce it in a single file I can run?

**Comment by excavador** [comment]
@kardianos 

```
ctx, cancel := context.WithCancel(context.Background())
defer cancel()

db, err := sql.OpenDB(...)
if err != nil {
	return err
}
defer db.Close()

db. SetMaxIdleConns(1)
db. SetMaxOpenConns(1)

for {
    var tx *sql.Tx
    if tx, err = db.BeginTx(ctx, nil); err != nil {
	  return err
   }
   // execute some long query
   tx.Commit()
   // small dely
}
return nil
```
During query execution close connection on MS SQL side.
Query execution returns driver.ErrBadConn, on next loop iteration BeginTx will panic

**Comment by kardianos** [comment]
@excavador 

Server is SQL Server 2019 (Linux). In `queries_go110_test.go` I added:
```

func TestBadConnection(t *testing.T) {
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*30)
	defer cancel()

	db := open(t)
	defer db.Close()

	db.SetMaxIdleConns(1)
	db.SetMaxOpenConns(1)

	ck := func(err error) (done bool) {
		switch err {
		default:
			t.Fatal(err)
			return true
		case nil:
			return false
		case context.Canceled, context.DeadlineExceeded:
			return true
		}
	}

	var err error
	for ctx.Err() == nil {
		func() {
			var tx *sql.Tx
			tx, err = db.BeginTx(ctx, nil)
			if ck(err) {
				return
			}
			defer tx.Rollback()

			// Execute "long" query.
			_, err = tx.ExecContext(ctx, "WAITFOR DELAY '00:00:01';")
			if ck(err) {
				return
			}

			err = tx.Commit()
			if ck(err) {
				return
			}

			// Wait for small delay.
			time.Sleep(time.Millisecond * 3)
		}()
	}
}
```

But I was unable to reproduce. Can you reproduce with this code or can you modify this snip to reproduce it? To test, you'll need to set the `SQLSERVER_DSN` env var.

**Comment by excavador** [comment]
Can not reproduce.
But I found the following: if you receive "EOF" error on BeginTx, it would panic after that
```
{"level":"info","ts":"2020-01-31T23:35:58.636Z","logger":"executor","caller":"external/org_bitbucket_projectname_backend/lib/namemssql/db.go:41","msg":"generic","mssql":{"printf":"ERROR: BeginRead faile
d EOF"}}
{"level":"error","ts":"2020-01-31T23:35:58.636Z","logger":"sqlhook.hook","caller":"external/com_github_denisenkom_go_mssqldb/mssql.go:184","msg":"panic","recover":"driver.ErrBadConn in checkBadConn. This should not happen.","stack":[
    "panic(0xc1c4c0, 0xf50be0)","\tGOROOT/src/runtime/panic.go:679 +0x1b2",
    "github.com/denisenkom/go-mssqldb.(*Conn).checkBadConn(0xc00288e580, 0xf61ac0, 0xc00007f5e0, 0xf61ac0, 0xc00007f5e0)","\texternal/com_github_denisenkom_go_mssqldb/mssql.go:184 +0x1ca",
    "github.com/denisenkom/go-mssqldb.(*Conn).begin(0xc00288e580, 0xf729a0, 0xc003f7a390, 0xc001a0c000, 0xd48f08, 0xc, 0xf729a0, 0xc003f7a390)","\texternal/com_github_denisenkom_go_mssqldb/mssql.go:288 +0xbb",
    "github.com/denisenkom/go-mssqldb.(*Conn).BeginTx(0xc00288e580, 0xf729a0, 0xc003f7a390, 0x0, 0xc00288e500, 0x0, 0x0, 0xf729a0, 0xc003f7a390)","\texternal/com_github_denisenkom_go_mssqldb/mssql.go:926 +0x7e",
    "database/sql.ctxDriverBegin(0xf72960, 0xc001a0c0c0, 0x0, 0xf6f1e0, 0xc0059e6640, 0x30, 0xd125e0, 0xc0021d5590, 0x42e2ca)",
    "\tGOROOT/src/database/sql/ctxutil.go:106 +0x9e","database/sql.(*DB).beginDC.func1()",
    "\tGOROOT/src/database/sql/sql.go:1705 +0x6b",
    "database/sql.withLock(0xf69260, 0xc003a8ad00, 0xc0021d55b8)",
    "\tGOROOT/src/database/sql/sql.go:3184 +0x6d",
    "database/sql.(*DB).beginDC(0xc002eee780, 0xf72960, 0xc001a0c0c0, 0xc003a8ad00, 0xc000030920, 0x0, 0x0, 0x0, 0x0)","\tGOROOT/src/database/sql/sql.go:1704 +0xa9","database/sql.(*Conn).BeginTx(0xc003f7a2a0, 0xf72960, 0xc001a0c0c0, 0x0, 0x0, 0x0, 0x7fd167e57fff)",
    "\tGOROOT/src/database/sql/sql.go:1909 +0xa4","bitbucket.org/projectname/backend/lib/namemssql.ActionTx.Db(0xc00200e460, 0xf72960, 0xc001a0c0c0, 0xc002eee780, 0xc0019ff140, 0x1d, 0x599, 0xc0002c5600, 0xd, 0xc0019ff1c0, ...)",
```

**Comment by excavador** [comment]
More details.

In case of unreliable network, if I list connection during the work and than trying to make request again
```
	var conn *sql.Conn
	if conn, err = db.Conn(ctx); err != nil {
		loggerExecutor.Error("conn failed", zap.Error(err))
		return
	}
	defer conn.Close()
	var tx *sql.Tx
	if tx, err = conn.BeginTx(ctx, nil); err != nil {
		return
	}
```
then I receive normal error.

But if I use following pattern:
```
	var tx *sql.Tx
	if tx, err = db.BeginTx(ctx, nil); err != nil {
		return
	}
	var complete bool
	defer func() {
		if complete && err == nil {
			if err = tx.Commit(); err != nil {
				loggerExecutor.Error("commit failed", zap.Error(err))
			}
		} else if err != sql.ErrTxDone && err != sql.ErrConnDone && err != driver.ErrBadConn {
			loggerExecutor.Error("rollback", zap.Error(err))
			err2 := tx.Rollback()
			if err2 != nil {
				loggerExecutor.Error("rollback failed", zap.Error(err2))
			} else {
				loggerExecutor.Info("rollback done")
			}
		} else {
			loggerExecutor.Error("action failed", zap.Error(err))
		}
	}()
	err = action(ctx, tx)
	complete = true
```
than golang sql try to get normal connection in the loop, and on cancelation of cancel I receive crash on rollback

```
{"level":"error","ts":"2020-02-11T02:48:45.765Z","logger":"sqlhook.Conn.PrepareContext","caller":"external/yyy/lib/sqlhook/zap/conn.go:260","msg":"failed","sqlhook":{"driver":"denisenkom/go-mssqldb","database":"xxx","worker_id":0,"error":"driver: bad connection"}}
...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8871d2]

goroutine 92276 [running]:
database/sql.(*Tx).rollback.func1()
	GOROOT/src/database/sql/sql.go:2112 +0x32
database/sql.withLock(0xf72580, 0xc003177980, 0xc001f58780)
	GOROOT/src/database/sql/sql.go:3184 +0x6d
database/sql.(*Tx).rollback(0xc0057ecc00, 0x1, 0xf7be80, 0xc005adad50)
	GOROOT/src/database/sql/sql.go:2111 +0x91
database/sql.(*Tx).awaitDone(0xc0057ecc00)
	GOROOT/src/database/sql/sql.go:2008 +0x5e
created by database/sql.(*DB).beginDC
	GOROOT/src/database/sql/sql.go:1723 +0x1b4
```

**Comment by dwj300** [comment]
@excavador, these details are very helpful - we are seeing the same pattern as you. We are still trying to reproduce. One thing - I think the crash on rollback you are seeing is different than the errBadConn panic that this issue describes. I think it would be worth filing a different issue for it, as that one is a nil pointer dereference.

**Comment by excavador** [comment]
@dwj300 we investigated the initial root of cause: we have side-to-side VPN between our daemon and MS SQL. We had wrongly configured IPSec, as result every 40 minutes VPN silently broke the connection, without any FIN package.

As result, ms sql driver going mad, it is not able to understand that connection broken and after that you can see all nested consequences from this ticket.

Seems like in this case happens something wrong with driver's logic.

**Comment by sevasm** [comment]
Hi all, after hitting this same issue and some investigation I've found the following:

The issue occurs when [sql.DB#BeginTx(context.Context, *sql.TxOptions)](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1723) is called after SQL server connection is closed by, for example, shutting down SQL server by stopping its Docker container. See [sevasm/go-mssqldb-panic](https://github.com/sevasm/go-mssqldb-panic) for an example program that can reproduce the issue reliably.

The issue cannot be reproduced by closing the underlying transport of the connection as is done in a number of tests, e.g. [TestCommitTranError (conn.sess.buf.transport.Close())](https://github.com/denisenkom/go-mssqldb/blob/master/queries_test.go#L1101).

After closing the underlying transport and calling [sql.DB#BeginTx(context.Context, *sql.TxOptions)](https://github.com/golang/go/blob/master/src/database/sql/sql.go#L1723), [#sendBeginXact(*tdsBuffer, []headerStruct, isoLevel, string, bool)](https://github.com/denisenkom/go-mssqldb/blob/master/tran.go#L31) is eventually called, and due to the closed transport returns an error.

However, when the connection is closed by stopping the SQLServer container, this method instead returns `nil`, indicating no error. Instead, an error is later received by [mssql.Conn#simpleProcessResp(context.Context)](https://github.com/denisenkom/go-mssqldb/blob/master/mssql.go#L203) on line [214](https://github.com/denisenkom/go-mssqldb/blob/master/mssql.go#L214). There, checkBadConn is called on the error and the "checked" error is returned. Eventually it propagates up to [mssql.Conn#begin(context.Context, isoLevel)](https://github.com/denisenkom/go-mssqldb/blob/master/mssql.go#L278) and is checked for a second time on line [288](https://github.com/denisenkom/go-mssqldb/blob/master/mssql.go#L288), causing the panic as it's already "checked" and is already a `driver.ErrBadConn` as indicated by the error message.

Because of how [mssql.Conn#simpleProcessResp(context.Context)](https://github.com/denisenkom/go-mssqldb/blob/master/mssql.go#L203) and [mssql.Conn#processBeginResponse(context.Context)](https://github.com/denisenkom/go-mssqldb/blob/master/mssql.go#L311) are implemented, I believe [mssql.Conn#begin(context.Context, isoLevel)](https://github.com/denisenkom/go-mssqldb/blob/master/mssql.go#L278) can only ever receive errors that are already "checked", therefore I have locally fixed the error by replacing line [288](https://github.com/denisenkom/go-mssqldb/blob/master/mssql.go#L288) of `mssql.go` with the following:

`return nil, err`

instead of

`return nil, c.checkBadConn(err)`

I can confirm that the panic no longer occurs after making this change, and all tests in the repository pass.

**Comment by excavador** [comment]
@sevasm wow! Thank you so much!
