### ISSUE TITLE
Support for LocalDB

### ISSUE THREAD

**Issue by FilipDeVos** [denisenkom/go-mssqldb#96]
This driver is unable to connect to SQL Server LocalDB instance. When you attempt to connect to localdb the following error is returned:

    Cannot connect:  Unable to get instances from Sql Server Browser on host (localdb): dial udp: GetAddrInfoW: No such host is known.

This is probably because a connection is attempted over tcp to the name (localdb), and LocalDB only supports named pipes. In this article https://msdn.microsoft.com/en-us/library/hh510202.aspx it is mentioned how to get the named pipe.

**Comment by denisenkom** [comment]
Named pipes and shared memory connections are not supported.  Only tcp connections are supported, you can enable tcp endpoint for your server to get it to work.

**Comment by FilipDeVos** [comment]
Thanks for the feedback. LocalDB only supports named pipes. Is supporting named pipes something that you would be interested in? (As far as I can see only jTDS has [an implementation](http://sourceforge.net/p/jtds/code/HEAD/tree/branches/jTDS%202.0%20%28experimental%29/src/java/net/sourceforge/jtds/jdbc/NamedPipeSocket.java) it uses jcifs for the grunt work in [SmbNamedPipe](https://jcifs.samba.org/src/src/jcifs/smb/SmbNamedPipe.java) which uses [SmbFileInputStream](https://jcifs.samba.org/src/src/jcifs/smb/SmbFileInputStream.java) and [SmbFileOutputStream](https://jcifs.samba.org/src/src/jcifs/smb/SmbFileOutputStream.java).
Note that jtds and jcifs are LGPL licensed, so that's a bit problematic with the BSD 3-clause license used by this project.)

**Comment by denisenkom** [comment]
There is a https://github.com/natefinch/npipe project which seems promising.
If you want you can implement it and send a pull request.

**Comment by denisenkom** [comment]
If you decide to implement it please make it a soft dependency on npipe, it should only be required if named pipes connection is requested by user.

**Comment by FilipDeVos** [comment]
I will give it a try. Still new at go so it might take some time to get somewhere.

**Comment by clns** [comment]
@FilipDeVos I'm also interested in this, have you been able to implement https://github.com/natefinch/npipe? Or made any progress whatsoever?

**Comment by FilipDeVos** [comment]
Not really no. Sorry

**Comment by simnalamburt** [comment]
I'm working on this issue at [simnalamburt/go-mssqldb](https://github.com/simnalamburt/go-mssqldb).

**Comment by kardianos** [comment]
I'm assuming you are also going to plug into the https://github.com/denisenkom/go-mssqldb/blob/8e6115d5172422909579b49fd1fe0f7591416e4b/tds.go#L24
SQL Server Browser to automatically choose named pipes?

**Comment by simnalamburt** [comment]
@kardianos Actually, I was editting `parseConnectParams` function. https://github.com/simnalamburt/go-mssqldb/commit/4ef9cb6d6

I'll let users to explicitly choose the protocol, rather than automatic detection. ADO driver does automatically choose protocol but it was misleading for many users.

**Comment by yusufozturk** [comment]
Thanks for the progress on this. So shared memory is not implemented yet, right? I read there was some good progress for that. (2 years ago) But it's kind of on hold now?

**Comment by simnalamburt** [comment]
@yusufozturk Yes I implemented named pipe feature in my fork (https://github.com/denisenkom/go-mssqldb/pull/250) but not the shared memory feature.

Actually implementing more conenction protocol is not that hard but I'm not using go-mssqldb anymore so I don't have enough motivation to implement it on my own.

**Comment by fortunewalla** [comment]
Not sure if this belongs here but I was told to ask you about a similar problem. I have problems connecting to LocalDB using DataStation CE software.

Below is a copy of the original issue: https://github.com/multiprocessio/datastation/issues/305

---------------------

SQL Server LocalDB  Instance : `(localdb)\MSSQLLocalDB`

So I entered the host as `(localdb)\MSSQLLocalDB` with `pubs` as the database. (This hostname works in Excel when connecting using SQL Server connection)

```sql
select 1+2;
```

It gives this error.

```
Error evaluating panel:
[INFO] 2023-08-20T22:49:28 DataStation Runner (Go) 0.11.0
[INFO] 2023-08-20T22:49:28 Evaling database panel: Untitled panel #1
[INFO] 2023-08-20T22:49:28 Failed to eval: parse "sqlserver://user:pass@(localdb)\\MSSQLLocalDB:1433?database=pubs": invalid character "\\" in host name
```


#### BTW it works with another similar software called DatabaseBrowser


![image](https://github.com/multiprocessio/datastation/assets/7158596/8bef8bec-df88-44e4-bbd8-60de879b3826)

-------------------

Also tried

`Server=127.0.0.1\MSSQLLocalDB`

and it gives a similar error.

```
Error evaluating panel:
[INFO] 2023-08-26T17:44:25 DataStation Runner (Go) 0.11.0
[INFO] 2023-08-26T17:44:25 Evaling database panel: Untitled panel #1
[INFO] 2023-08-26T17:44:25 Failed to eval: parse "sqlserver://@Server=127.0.0.1\\MSSQLLocalDB:1433?database=pubs": invalid character "\\" in host name
```

Any ideas for resolving this? It seems to a case of not being able to parse the backslash character properly `\`.

Hope this helps in anyway. Thanks.

**Comment by FilipDeVos** [comment]
You're trying to connect with TCP/IP by specifying the port number .
Localdb only supports connecting with named pipes.

You can force a named pipes connection by prefixing your server name with
np:

Read this for more info:
https://weblogs.asp.net/jongalloway/sql-force-the-protocol-tcp-named-pipes-etc-in-your-connection-string

**Comment by fortunewalla** [comment]
> You're trying to connect with TCP/IP by specifying the port number . Localdb only supports connecting with named pipes. You can force a named pipes connection by prefixing your server name with np: 
So as per the suggestion given on this page

I tried with the connection string `Server=np:(localdb)\MSSQLLocalDB`

It now gives a different error where it parses everything after `:` as a port number.

```
Error evaluating panel:
[INFO] 2023-08-27T16:40:05 DataStation Runner (Go) 0.11.0
[INFO] 2023-08-27T16:40:05 Evaling database panel: Untitled panel #1
[INFO] 2023-08-27T16:40:05 Failed to eval: parse "sqlserver://@Server=np:(localdb)\\MSSQLLocalDB?database=pubs": invalid port ":(localdb)\\MSSQLLocalDB" after host
```

I also tried `np:127.0.0.1`

```
Error evaluating panel:
[INFO] 2023-08-27T16:45:56 DataStation Runner (Go) 0.11.0
[INFO] 2023-08-27T16:45:56 Evaling database panel: Untitled panel #1
[INFO] 2023-08-27T16:45:56 Failed to eval: parse "sqlserver://@Server=np:127.0.0.1?database=pubs": invalid port ":127.0.0.1" after host
```

**Comment by fortunewalla** [comment]
I also tried specifying the port number explicitly.

`np:(localdb)\MSSQLLocalDB:1433`

It gives this error

```yml
Error evaluating panel:
[INFO] 2023-08-27T16:50:50 DataStation Runner (Go) 0.11.0
[INFO] 2023-08-27T16:50:50 Evaling database panel: Untitled panel #1
[INFO] 2023-08-27T16:50:50 Failed to eval: DSError {
  "name": "Error",
  "message": "Could not split host-port: address np:(localdb)\\MSSQLLocalDB:1433: too many colons in address",
  "stack": "goroutine 1 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/multiprocessio/datastation/runner.makeErrException({0x285f2e0?, 0xc000ead9d0?})\n\tgithub.com/multiprocessio/datastation/runner/errors.go:81 +0x5c\ngithub.com/multiprocessio/datastation/runner.edsef({0x244eade?, 0x1e?}, {0xc000bfef88?, 0x1?, 0x0?})\n\tgithub.com/multiprocessio/datastation/runner/errors.go:89 +0x32\ngithub.com/multiprocessio/datastation/runner.getDatabaseHostPortExtra({0xc000973de0?, 0xc000e228a0?}, {0x241d546, 0x4})\n\tgithub.com/multiprocessio/datastation/runner/database.go:37 +0x112\ngithub.com/multiprocessio/datastation/runner.EvalContext.EvalDatabasePanel({{{0xc000cc2407, 0xc}, 0xc000e62380, 0xc000e22c90, {0xc000cc24d8, 0x34}, 0x1388, {0xc000cc2549, 0x4}, {0x37d1808, ...}}, ...}, ...)\n\tgithub.com/multiprocessio/datastation/runner/database.go:470 +0x1405\ngithub.com/multiprocessio/datastation/runner.EvalContext.Eval({{{0xc000cc2407, 0xc}, 0xc000e62380, 0xc000e22c90, {0xc000cc24d8, 0x34}, 0x1388, {0xc000cc2549, 0x4}, {0x37d1808, ...}}, ...}, ...)\n\tgithub.com/multiprocessio/datastation/runner/eval.go:209 +0x878\nmain.eval({{{0xc000cc2407, 0xc}, 0xc000e62380, 0xc000e22c90, {0xc000cc24d8, 0x34}, 0x1388, {0xc000cc2549, 0x4}, {0x37d1808, ...}}, ...}, ...)\n\t./main.go:88 +0x7b\nmain.main()\n\t./main.go:126 +0x25e\n",
  "targetPanelId": "",
  "extra": null
}
goroutine 1 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/multiprocessio/datastation/runner.makeErrException({0x285f2e0?, 0xc000ead9d0?})
	github.com/multiprocessio/datastation/runner/errors.go:81 +0x5c
github.com/multiprocessio/datastation/runner.edsef({0x244eade?, 0x1e?}, {0xc000bfef88?, 0x1?, 0x0?})
	github.com/multiprocessio/datastation/runner/errors.go:89 +0x32
github.com/multiprocessio/datastation/runner.getDatabaseHostPortExtra({0xc000973de0?, 0xc000e228a0?}, {0x241d546, 0x4})
	github.com/multiprocessio/datastation/runner/database.go:37 +0x112
github.com/multiprocessio/datastation/runner.EvalContext.EvalDatabasePanel({{{0xc000cc2407, 0xc}, 0xc000e62380, 0xc000e22c90, {0xc000cc24d8, 0x34}, 0x1388, {0xc000cc2549, 0x4}, {0x37d1808, ...}}, ...}, ...)
	github.com/multiprocessio/datastation/runner/database.go:470 +0x1405
github.com/multiprocessio/datastation/runner.EvalContext.Eval({{{0xc000cc2407, 0xc}, 0xc000e62380, 0xc000e22c90, {0xc000cc24d8, 0x34}, 0x1388, {0xc000cc2549, 0x4}, {0x37d1808, ...}}, ...}, ...)
	github.com/multiprocessio/datastation/runner/eval.go:209 +0x878
main.eval({{{0xc000cc2407, 0xc}, 0xc000e62380, 0xc000e22c90, {0xc000cc24d8, 0x34}, 0x1388, {0xc000cc2549, 0x4}, {0x37d1808, ...}}, ...}, ...)
	./main.go:88 +0x7b
main.main()
	./main.go:126 +0x25e
```

**Comment by FilipDeVos** [comment]
The db driver you are using doesn't support named pipes. So it's never
going to work.

**Comment by fortunewalla** [comment]
> The db driver you are using doesn't support named pipes. So it's never going to work.

I was told that it is this library `go-mssqldb` that they are using but I guess it is not possible.

Thanks for your quick replies to all these. 🙏🏼
